use master
IF EXISTS(SELECT * FROM sys.databases WHERE name = 'ICETASK')
DROP DATABASE ICETASK
CREATE DATABASE ICETASK
use ICETASK

CREATE TABLE Student(
StudentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
StudentNumber VARCHAR(10) UNIQUE NOT NULL,
FullName VARCHAR(250) NOT NULL,
Programme VARCHAR(MAX) NOT NULL
);